<?php

declare(strict_types=1);
use Docuccino\Core\Inference\TypeEngine;
use Docuccino\Core\Pipeline\GenerationResult;
use Docuccino\Laravel\Config\DocumentConfigFactory;
use Docuccino\Laravel\Pipeline\DocumentGenerator;
use Docuccino\Laravel\Tests\Support\WorkbenchEngine;
use Docuccino\Laravel\Tests\TestCase;

/*
 * Monorepo Pest bootstrap. Test files live alongside their package
 * (packages/<pkg>/tests); this root file binds Pest's test case to them and exposes
 * shared fixture helpers.
 */

uses()->in(dirname(__DIR__).'/packages/core/tests');
uses(TestCase::class)->in(dirname(__DIR__).'/packages/laravel/tests');

/**
 * Bind the deterministic workbench stub {@see TypeEngine} the Laravel feature tests build against.
 */
function bindStubEngine(): void
{
    app()->instance(TypeEngine::class, WorkbenchEngine::make());
}

/**
 * Build the `default` workbench document, optionally mutating its raw config first. The single
 * shared build helper the Laravel feature tests use instead of each re-rolling the config →
 * generator wiring (and coupling across files via a peer test's global function).
 *
 * @param  callable(array<string, mixed>): array<string, mixed>|null  $mutateConfig
 */
function generateDocument(?callable $mutateConfig = null): GenerationResult
{
    /** @var array<string, mixed> $raw */
    $raw = config('docuccino.documents.default');
    if ($mutateConfig !== null) {
        $raw = $mutateConfig($raw);
    }

    $config = app(DocumentConfigFactory::class)->make('default', $raw, 'skeleton');

    return app(DocumentGenerator::class)->generate($config, app(TypeEngine::class));
}

/**
 * Index an emitted operation's parameters by name (the shape every parameter-asserting feature test
 * needs). Promoted here so suites don't couple to a peer test's file-level global.
 *
 * @return array<string, array<string, mixed>>
 */
function paramsByName(array $operation): array
{
    $byName = [];
    foreach ($operation['parameters'] ?? [] as $parameter) {
        $byName[$parameter['name']] = $parameter;
    }

    return $byName;
}

/**
 * @return array<string, mixed>
 */
function loadFixture(string $name): array
{
    $path = dirname(__DIR__).'/packages/core/tests/Fixtures/'.$name;
    $contents = file_get_contents($path);

    if ($contents === false) {
        throw new RuntimeException('Fixture not found: '.$path);
    }

    /** @var array<string, mixed> $decoded */
    $decoded = json_decode($contents, true, flags: JSON_THROW_ON_ERROR);

    return $decoded;
}

/**
 * @return array<string, mixed>
 */
function workedExample(): array
{
    return loadFixture('worked-example.json');
}

/**
 * A maximal valid UIR document exercising every modelled surface (requestBody, securitySchemes +
 * operation-level security, servers with variables, webhooks, path/header/cookie params, the 3.2
 * `query` method, multiple media types, examples, externalDocs, deprecated, content pages, floats
 * and unicode keys).
 *
 * @return array<string, mixed>
 */
function kitchenSink(): array
{
    return loadFixture('kitchen-sink.uir.json');
}

/**
 * Reads a committed golden artifact byte-for-byte.
 */
function loadGolden(string $name): string
{
    $path = dirname(__DIR__).'/packages/core/tests/Fixtures/golden/'.$name;
    $contents = file_get_contents($path);

    if ($contents === false) {
        throw new RuntimeException('Golden not found: '.$path);
    }

    return $contents;
}

/**
 * Path of a committed Laravel-adapter golden (shared by ExportTest/ContentTest).
 */
function golden(string $name): string
{
    return dirname(__DIR__).'/packages/laravel/tests/Fixtures/golden/'.$name;
}

/**
 * Reads a golden, or (under DOCUCCINO_UPDATE_GOLDEN=1) writes the freshly generated bytes first.
 */
function assertGolden(string $name, string $actual): void
{
    $path = golden($name);
    if (getenv('DOCUCCINO_UPDATE_GOLDEN') === '1') {
        @mkdir(dirname($path), 0777, true);
        file_put_contents($path, $actual);
    }

    expect($actual)->toBe(file_get_contents($path));
}

/**
 * A rich base document (extends the design §11 worked example): one operation with a path param,
 * a query param carrying an enum, a JSON response with an object schema, an error response, a
 * named component schema, and a content page — enough surface to exercise every diff rule.
 *
 * @return array<string, mixed>
 */
function diffBase(): array
{
    return [
        'uir' => '1.0.0',
        'openapi' => '3.2.0',
        'info' => ['title' => 'Forms API', 'version' => '1.0.0'],
        'paths' => [
            '/api/v1/forms/{id}' => [
                'get' => [
                    'x-docuccino' => ['id' => 'op:v1:aaaaaaaaaaaaaaaa'],
                    'operationId' => 'forms.show',
                    'summary' => 'Show a form',
                    'tags' => ['Forms'],
                    'parameters' => [
                        [
                            'x-docuccino' => ['id' => 'par:v1:bbbbbbbbbbbbbbbb'],
                            'name' => 'id', 'in' => 'path', 'required' => true,
                            'schema' => ['type' => 'integer'],
                        ],
                        [
                            'x-docuccino' => ['id' => 'par:v1:cccccccccccccccc'],
                            'name' => 'status', 'in' => 'query', 'required' => false,
                            'schema' => ['type' => 'string', 'enum' => ['draft', 'published', 'archived']],
                        ],
                    ],
                    'responses' => [
                        '200' => [
                            'x-docuccino' => ['id' => 'res:v1:dddddddddddddddd'],
                            'description' => 'The form',
                            'content' => [
                                'application/json' => [
                                    'schema' => [
                                        'type' => 'object',
                                        'properties' => [
                                            'id' => ['type' => 'integer'],
                                            'title' => ['type' => 'string'],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                        '404' => ['description' => 'Not found'],
                    ],
                ],
            ],
        ],
        'components' => [
            'schemas' => [
                'FormData' => [
                    'x-docuccino' => ['id' => 'sch:v1:eeeeeeeeeeeeeeee'],
                    'type' => 'object',
                    'properties' => ['id' => ['type' => 'integer']],
                ],
            ],
        ],
        'x-docuccino' => [
            'content' => [
                'pages' => [
                    ['id' => 'page:v1:ffffffffffffffff', 'slug' => 'getting-started', 'title' => 'Getting started', 'content' => 'Welcome.'],
                ],
            ],
        ],
    ];
}

/**
 * Recursively strips every `x-docuccino` member and the UIR-only top-level `$schema`/`uir`, so the
 * remainder is exactly what a lossless OAS 3.2 transcode must equal.
 *
 * @param  array<string, mixed>  $node
 * @return array<string, mixed>
 */
function stripDocuccino(array $node): array
{
    unset($node['x-docuccino']);

    $out = [];
    foreach ($node as $key => $value) {
        $key = (string) $key;
        $out[$key] = str_starts_with($key, 'x-') ? $value : stripDocuccinoRecursive($value);
    }

    return $out;
}

function stripDocuccinoRecursive(mixed $value): mixed
{
    if (! is_array($value)) {
        return $value;
    }

    if (array_is_list($value)) {
        return array_map(stripDocuccinoRecursive(...), $value);
    }

    return stripDocuccino($value);
}

/**
 * Gate for the fixture-app-dependent integration tests. Normally a missing
 * fixture app skips the test (contributors without it still get a green local
 * run). Under `DOCUCCINO_REQUIRE_FIXTURE=1` — the CI fixture job — a missing
 * fixture app is instead a hard FAILURE, so the suite can never silently pass by
 * skipping the very tests the job exists to run.
 */
function ensureFixtureAvailable(bool $available): void
{
    if ($available) {
        return;
    }

    if (getenv('DOCUCCINO_REQUIRE_FIXTURE') === '1') {
        throw new RuntimeException(
            'Fixture app required (DOCUCCINO_REQUIRE_FIXTURE=1) but absent — provision per tests/fixture-app/setup.md',
        );
    }

    test()->markTestSkipped('fixture app absent — recreate per tests/fixture-app/setup.md');
}
