// @ts-check
import { copyFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLlmsTxt from 'starlight-llms-txt';
import starlightMdTxt from 'starlight-md-txt';

// starlight-md-txt routes its Markdown twins as `[...slug].md`, so the landing page — whose slug is
// empty — lands on the hidden path `/.md`. Copy it to the conventional `/index.md` as well, so the
// root page is reachable by the name a reader (or a crawler) would actually try. Every other page
// already follows "page URL + .md".
const indexMarkdownAlias = {
	name: 'docuccino-index-markdown-alias',
	hooks: {
		'astro:build:done': ({ dir }) => {
			const hidden = fileURLToPath(new URL('./.md', dir));
			if (existsSync(hidden)) {
				copyFileSync(hidden, fileURLToPath(new URL('./index.md', dir)));
			}
		},
	},
};

// https://astro.build/config
export default defineConfig({
	// Static output (Astro's default — no `output` or `adapter` key). The site is a pure content
	// site: there are no `src/pages`, no endpoints and no request-time APIs, so nothing here needs a
	// server. GitHub Pages serves the built `dist/` directly.
	//
	// No `base`: the site is served from the root of its own custom domain (see public/CNAME), so
	// paths stay identical to the URLs already published in every package README. A project-page
	// deploy would need `base: '/docuccino'` and would move every URL.
	site: 'https://docs.docuccino.app',
	// The bundled Scalar viewer on the landing page is a large, intentional client chunk; lift the
	// size-warning threshold so it doesn't flag on every build.
	vite: {
		build: { chunkSizeWarningLimit: 3000 },
	},
	integrations: [
		indexMarkdownAlias,
		starlight({
			title: 'Docuccino',
			description:
				'UIR-based API documentation generator for Laravel: deep type inference, deterministic output, semantic diffing and a bundled Scalar viewer.',
			// Machine-readable copies of the docs, for readers who arrive as an AI assistant rather
			// than in a browser: llms-txt builds the /llms*.txt digests, md-txt writes a .md twin
			// beside every page. Both are build-time only — no runtime, no request-time work.
			plugins: [
				starlightLlmsTxt({
					description:
						'Docuccino is an open-source (MIT) API documentation generator for Laravel. It compiles an application into a UIR (Universal Intermediate Representation — an OpenAPI-3.2-shaped, deterministic, identity-carrying JSON document) and emits OpenAPI 3.2/3.1/3.0, with semantic diffing and a bundled Scalar viewer.',
					details: [
						'## Key facts',
						'',
						'- Install: `composer require docuccino/laravel` plus `composer require --dev docuccino/inference-phpstan` (the analysis engine is a dev dependency; the adapter degrades to no inference without it).',
						'- Requirements: PHP 8.3+, Laravel 12 or 13.',
						'- Commands: `docuccino:export`, `docuccino:validate`, `docuccino:diff`, `docuccino:cache`, `docuccino:clear`.',
						'- Config lives in one published file, `config/docuccino.php`, organized around named `documents`.',
						'- Docuccino never executes application code — it reads types with an embedded PHPStan/Larastan engine.',
						'- Output is byte-deterministic, so the exported document is meant to be committed and diffed.',
						'- Precedence, lowest to highest: fallback, inference, integration, docblock, attribute, overlay, config. Higher layers win field by field.',
					].join('\n'),
					// Pages ordered for a reader starting from zero.
					promote: ['index*', 'laravel/getting-started*', 'laravel/guides/how-it-works*'],
					// The small variant is for tight context windows: keep the task-shaped pages, drop
					// the migration/comparison material and the spec-hosting detail.
					exclude: ['guides/vs-*', 'uir/hosting*'],
				}),
				starlightMdTxt(),
			],
			logo: {
				// The task-specified mapping: light theme → logo-light.svg, dark theme → logo.svg.
				light: './src/assets/logo-light.svg',
				dark: './src/assets/logo.svg',
				replacesTitle: true,
				alt: 'Docuccino',
			},
			favicon: '/icon.svg',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/docuccino/docuccino' },
			],
			editLink: {
				baseUrl: 'https://github.com/docuccino/docuccino/edit/main/website/',
			},
			// The sidebar is deliberate: labels and order are set here, not autogenerated, so the
			// Laravel content path-scoping (laravel/*) stays invisible to readers and package-named
			// entries mirror the ecosystems developers already know. When a second framework ships,
			// this becomes a starlight-sidebar-topics switcher without moving a single URL.
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'Installation', slug: 'laravel/getting-started' },
						{ label: 'Your first export', slug: 'laravel/getting-started/first-export' },
					],
				},
				{
					label: 'Documenting your API',
					items: [
						{ label: 'Overview', slug: 'laravel/documenting' },
						{ label: 'Requests', slug: 'laravel/documenting/requests' },
						{ label: 'Responses', slug: 'laravel/documenting/responses' },
						{ label: 'Resources, models & enums', slug: 'laravel/documenting/schemas' },
						{ label: 'Error responses', slug: 'laravel/documenting/errors' },
						{ label: 'Authentication', slug: 'laravel/documenting/authentication' },
						{ label: 'Rate limiting', slug: 'laravel/documenting/rate-limiting' },
					],
				},
				{
					label: 'Package support',
					items: [
						{ label: 'Overview', slug: 'laravel/packages' },
						{ label: 'Spatie Data', slug: 'laravel/packages/spatie-data' },
						{ label: 'Spatie Query Builder', slug: 'laravel/packages/query-builder' },
						{ label: 'Laravel Actions', slug: 'laravel/packages/laravel-actions' },
						{ label: 'JSON:API resources', slug: 'laravel/packages/timacdonald-json-api' },
						{ label: 'Spatie JSON API Paginate', slug: 'laravel/packages/json-api-paginate' },
						{ label: 'Spatie Laravel Permission', slug: 'laravel/packages/laravel-permission' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'How it works', slug: 'laravel/guides/how-it-works' },
						{ label: 'Deploying to production', slug: 'laravel/guides/production' },
						{ label: 'Multiple documents', slug: 'laravel/guides/multiple-documents' },
						{ label: 'Customizing the output', slug: 'laravel/guides/customizing-output' },
						{ label: 'Guides, pages & prose', slug: 'laravel/guides/narrative-content' },
						{ label: 'The viewer', slug: 'laravel/guides/viewer' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Configuration reference', slug: 'laravel/reference/configuration' },
						{ label: 'Commands', slug: 'laravel/reference/commands' },
						{ label: 'Attributes reference', slug: 'laravel/reference/attributes' },
					],
				},
				{
					label: 'Extending',
					items: [{ label: 'Writing an integration', slug: 'extending/extension-authoring' }],
				},
				{
					label: 'Comparisons',
					items: [
						{ label: 'Docuccino vs Scramble', slug: 'guides/vs-scramble' },
						{ label: 'Docuccino vs Scribe', slug: 'guides/vs-scribe' },
					],
				},
				{
					label: 'UIR spec',
					items: [{ autogenerate: { directory: 'uir' } }],
				},
			],
		}),
	],
});
