// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://docs.docuccino.app',
	// The bundled Scalar viewer on the landing page is a large, intentional client chunk; lift the
	// size-warning threshold so it doesn't flag on every build.
	vite: {
		build: { chunkSizeWarningLimit: 3000 },
	},
	integrations: [
		starlight({
			title: 'Docuccino',
			description:
				'UIR-based API documentation generator for Laravel: tier-3 inference, deterministic output, semantic diffing and a bundled Scalar viewer.',
			logo: {
				// The task-specified mapping: light theme → logo-light.svg, dark theme → logo.svg.
				light: './src/assets/logo-light.svg',
				dark: './src/assets/logo.svg',
				replacesTitle: true,
				alt: 'Docuccino',
			},
			favicon: '/icon.svg',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/docuccino/docuccino' },
			],
			editLink: {
				baseUrl: 'https://github.com/docuccino/docuccino/edit/main/website/',
			},
			// The sidebar is deliberate: labels and order are set here, not autogenerated, so the
			// Laravel content path-scoping (laravel/*) stays invisible to readers and package-named
			// entries mirror the ecosystems developers already know. When a second framework ships,
			// this becomes a starlight-sidebar-topics switcher without moving a single URL.
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'Installation', slug: 'laravel/getting-started' },
						{ label: 'Your first export', slug: 'laravel/getting-started/first-export' },
					],
				},
				{
					label: 'Documenting your API',
					items: [
						{ label: 'Overview', slug: 'laravel/documenting' },
						{ label: 'Requests', slug: 'laravel/documenting/requests' },
						{ label: 'Responses', slug: 'laravel/documenting/responses' },
						{ label: 'Resources, models & enums', slug: 'laravel/documenting/schemas' },
						{ label: 'Error responses', slug: 'laravel/documenting/errors' },
						{ label: 'Authentication', slug: 'laravel/documenting/authentication' },
						{ label: 'Rate limiting', slug: 'laravel/documenting/rate-limiting' },
					],
				},
				{
					label: 'Package support',
					items: [
						{ label: 'Spatie Data', slug: 'laravel/packages/spatie-data' },
						{ label: 'Spatie Query Builder', slug: 'laravel/packages/query-builder' },
						{ label: 'Laravel Actions', slug: 'laravel/packages/laravel-actions' },
						{ label: 'JSON:API resources', slug: 'laravel/packages/timacdonald-json-api' },
						{ label: 'Spatie JSON API Paginate', slug: 'laravel/packages/json-api-paginate' },
						{ label: 'Spatie Laravel Permission', slug: 'laravel/packages/laravel-permission' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'How it works', slug: 'laravel/guides/how-it-works' },
						{ label: 'Deploying to production', slug: 'laravel/guides/production' },
						{ label: 'Multiple documents', slug: 'laravel/guides/multiple-documents' },
						{ label: 'Customizing the output', slug: 'laravel/guides/customising-output' },
						{ label: 'Guides, pages & prose', slug: 'laravel/guides/narrative-content' },
						{ label: 'The viewer', slug: 'laravel/guides/viewer' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Configuration reference', slug: 'laravel/reference/configuration' },
						{ label: 'Commands', slug: 'laravel/reference/commands' },
						{ label: 'Attributes reference', slug: 'laravel/reference/attributes' },
					],
				},
				{
					label: 'Extending',
					items: [{ label: 'Writing an integration', slug: 'extending/extension-authoring' }],
				},
				{
					label: 'Comparisons',
					items: [
						{ label: 'Docuccino vs Scramble', slug: 'guides/vs-scramble' },
						{ label: 'Docuccino vs Scribe', slug: 'guides/vs-scribe' },
					],
				},
				{
					label: 'UIR spec',
					items: [{ autogenerate: { directory: 'uir' } }],
				},
			],
		}),
	],
});
